### ISSUE TITLE
大神，我所有的环境按照你的教程安装了，但是好像连接不上数据库，就是不能自动创建表。

### ISSUE THREAD

**Issue by Coder-Ali** [liangfengbo/nodejs-koa2-mysql-sequelize-jwt#13]
一直报错误Unhandled rejection SequelizeConnectionError: connect ETIMEDOUT     at Utils.Promise.tap.then.catch.err (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)

**Comment by Coder-Ali** [comment]
后台登录接口报这个错误

Error
Looks like something broke!

        
SequelizeConnectionError: connect ETIMEDOUT
    at Utils.Promise.tap.then.catch.err (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:149:19)
    at tryCatcher (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/ali/Projects/nodejs-koa2-mysql-sequelize-jwt/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
